// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSystem_PoC.Data.Context;

namespace ReservationSystem_PoC.Data.Migrations
{
    [DbContext(typeof(ReservarionSystemDbContext))]
    [Migration("20201207112218_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BirthDate");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("DateOfChange");

                    b.HasIndex("DateOfCreation");

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Valid");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.ContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DateOfChange");

                    b.HasIndex("DateOfCreation");

                    b.HasIndex("Description");

                    b.HasIndex("Valid");

                    b.ToTable("ContactType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea190d3f-6288-4277-93d6-8dd72cd7c76b"),
                            DateOfChange = new DateTime(2020, 12, 7, 11, 22, 17, 645, DateTimeKind.Utc).AddTicks(9113),
                            DateOfCreation = new DateTime(2020, 12, 7, 11, 22, 17, 645, DateTimeKind.Utc).AddTicks(9678),
                            Description = "Contact Type 1",
                            Valid = true
                        },
                        new
                        {
                            Id = new Guid("bea4bd1a-0c70-421a-95f7-4822855c1a09"),
                            DateOfChange = new DateTime(2020, 12, 7, 11, 22, 17, 646, DateTimeKind.Utc).AddTicks(802),
                            DateOfCreation = new DateTime(2020, 12, 7, 11, 22, 17, 646, DateTimeKind.Utc).AddTicks(803),
                            Description = "Contact Type 2",
                            Valid = true
                        },
                        new
                        {
                            Id = new Guid("e3c2843d-909c-4a27-a941-7749f3d5ea9c"),
                            DateOfChange = new DateTime(2020, 12, 7, 11, 22, 17, 646, DateTimeKind.Utc).AddTicks(808),
                            DateOfCreation = new DateTime(2020, 12, 7, 11, 22, 17, 646, DateTimeKind.Utc).AddTicks(809),
                            Description = "Contact Type 3",
                            Valid = true
                        });
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Favorited")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("DateOfChange");

                    b.HasIndex("DateOfCreation");

                    b.HasIndex("Favorited");

                    b.HasIndex("Ranking");

                    b.HasIndex("Valid");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Contact", b =>
                {
                    b.HasOne("ReservationSystem_PoC.Domain.Core.Entities.ContactType", "ContactType")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationSystem_PoC.Domain.Core.Entities.Contact", "Contact")
                        .WithMany("Reservations")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Contact", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.ContactType", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
