// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ReservationSystem_PoC.Data.Context;
using System;

namespace ReservationSystem_PoC.Data.Migrations
{
    [DbContext(typeof(ReservarionSystemDbContext))]
    partial class ReservarionSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BirthDate");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("DateOfChange");

                    b.HasIndex("DateOfCreation");

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Valid");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.ContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DateOfChange");

                    b.HasIndex("DateOfCreation");

                    b.HasIndex("Description");

                    b.HasIndex("Valid");

                    b.ToTable("ContactType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("044ba27e-e1c4-4f90-bd6c-e9407c29a270"),
                            DateOfChange = new DateTime(2020, 12, 11, 14, 12, 22, 424, DateTimeKind.Utc).AddTicks(7309),
                            DateOfCreation = new DateTime(2020, 12, 11, 14, 12, 22, 424, DateTimeKind.Utc).AddTicks(7969),
                            Description = "Contact Type 1",
                            Valid = true
                        },
                        new
                        {
                            Id = new Guid("08d214bc-6d93-4a8d-9cd3-20c40b292298"),
                            DateOfChange = new DateTime(2020, 12, 11, 14, 12, 22, 424, DateTimeKind.Utc).AddTicks(9326),
                            DateOfCreation = new DateTime(2020, 12, 11, 14, 12, 22, 424, DateTimeKind.Utc).AddTicks(9327),
                            Description = "Contact Type 2",
                            Valid = true
                        },
                        new
                        {
                            Id = new Guid("f1faac37-c05b-41f6-a3c6-8635f6dc6b86"),
                            DateOfChange = new DateTime(2020, 12, 11, 14, 12, 22, 424, DateTimeKind.Utc).AddTicks(9332),
                            DateOfCreation = new DateTime(2020, 12, 11, 14, 12, 22, 424, DateTimeKind.Utc).AddTicks(9333),
                            Description = "Contact Type 3",
                            Valid = true
                        });
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Favorited")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("DateOfChange");

                    b.HasIndex("DateOfCreation");

                    b.HasIndex("Favorited");

                    b.HasIndex("Ranking");

                    b.HasIndex("Valid");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Contact", b =>
                {
                    b.HasOne("ReservationSystem_PoC.Domain.Core.Entities.ContactType", "ContactType")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationSystem_PoC.Domain.Core.Entities.Contact", "Contact")
                        .WithMany("Reservations")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.Contact", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ReservationSystem_PoC.Domain.Core.Entities.ContactType", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
